### ISSUE TITLE
Module 1 not launching

### ISSUE THREAD

**Issue by DCTN-FS** [rstudio-education/shiny-course#16]
Hi there,
clicking on Module 1 from this [webpage ](https://rstudio-education.github.io/shiny-course/) shows this error message in both Firefox and Chrome : 
**An error has occurred
The application failed to start.
exit status 1**
I cannot be sure if this could be due to my office's network limitations but just in case can you check if anything is wrong with that [URL](https://minecr.shinyapps.io/01-hello/).
Thanks for everything.

**Comment by mine-cetinkaya-rundel** [comment]
Should be back up and running now!

**Comment by DCTN-FS** [comment]
Thanks a lot for your work.
