### ISSUE TITLE
Feedback on 01-hello

### ISSUE THREAD

**Issue by cwickham** [rstudio-education/shiny-course#2]
This is a really great intro - and I appreciate a ton of work has gone into it.  Thank you!

There were a few things I caught as I worked through this section:

* https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L186
    There are no input sliders in the app at this point.  

* https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L187 
     I think this is asking me to change the code, but it feels like a big ask of someone who is seeing this code for the first time.  Some questions that I think would arise:
    * How do I get back to my code? (E.g. the app is probably running in a pop up window, should I close it?)
    * Where and what am I changing? I need to identify the chunk that corresponds to the "`y` input", find the `selected` argument inside, then need to recognize I need to replace `"audience_score"` with `"imdb_rating"`.  If I fail at any of those steps, I'm not going to have much luck repeating them for the `x` input.
    * How do "rerun" the app? 
    * What do I do if it doesn't work?

* Something is out of sync between the code shown in the text, and the code I see in the cloud, for 1-2b Extend the UI further: https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L387
    The code I see in the cloud, requires me to pick an `inputId` and edit `server` to use that in the plotting code.
    <details>
    <summary>Code I see in `app.R`</summary>
    <pre>
    # Load packages ----------------------------------------------------------------
    
    library(shiny)
    library(ggplot2)
    
    # Load data --------------------------------------------------------------------
    
    load("movies.RData")
    
    # Define UI --------------------------------------------------------------------
    
    ui <- fluidPage(
      
      sidebarLayout(
        
        # Inputs: Select variables to plot
        sidebarPanel(
          
          # Select variable for y-axis
          selectInput(inputId = "y", 
                      label = "Y-axis:",
                      choices = c("imdb_rating", "imdb_num_votes", "critics_score", "audience_score", "runtime"), 
                      selected = "audience_score"),
          
          # Select variable for x-axis
          selectInput(inputId = "x", 
                      label = "X-axis:",
                      choices = c("imdb_rating", "imdb_num_votes", "critics_score", "audience_score", "runtime"), 
                      selected = "critics_score"),
          
          # Select variable for color
          selectInput(inputId = "___", 
                      label = "____",
                      choices = c(___),
                      selected = "___")
          
        ),
        
        # Output: Show scatterplot
        mainPanel(
          plotOutput(outputId = "scatterplot")
        )
      )
    )
    
    # Define server ----------------------------------------------------------------
    
    server <- function(input, output, session) {
      
      output$scatterplot <- renderPlot({
        ggplot(data = movies, aes_string(x = input$x, y = input$y,
                                         color = ___)) +
          geom_point()
      })
      
    }
    
    # Create a Shiny app object ----------------------------------------------------
    
    shinyApp(ui = ui, server = server)
    </pre>
    </details>
    If the code in the text is correct, it might help to tell learners up front to give this the id `"z"`.

* It feels like a lot just got covered about the relationship between inputs and outputs, ui and server, by the point you talk about reactivity: https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L781
    Is it worth having a quick task that helps cement the idea of the link between inputs and outputs?

* This is pretty hard: https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L828-L829
    I know my way around an app, and it still took me a few tries to find all the problems, with a lot of cryptic error messages in between.  Perhaps some hints here might help.  Maybe break the problems into sub tasks, or questions like:     Do the render functions match the output functions? Are the inputs referred to using the correct syntax? Are the outputs referred to using the correct names?
    
    Now I write that I realise these are basically outlined in "Rules of server functions", so perhaps reminding people of that list, then getting helping them to focus on parts of the script might help.  It feels like getting someone to check all three inputs, and an output is quite a lot of code to review.

* https://github.com/rstudio-education/shiny-course/blob/0fe1fafa19883f02ff788634ac7e49fb125fd936/01-hello/01-hello.Rmd#L1010 
    Most of the content in this section isn't recap, it is new.  Perhaps lead with the recap, then introduce some "Tips", or rename the section.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you so much for the feedback @cwickham! I addressed your comments in the commit above and redeployed the tutorial.
